package com.admin.mall.mbg.mapper;

import com.admin.mall.mbg.model.OmsOrderItem;
import com.admin.mall.mbg.model.OmsOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int countByExample(OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int deleteByExample(OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int insert(OmsOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int insertSelective(OmsOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    List<OmsOrderItem> selectByExample(OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    OmsOrderItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") OmsOrderItem record, @Param("example") OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int updateByExample(@Param("record") OmsOrderItem record, @Param("example") OmsOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int updateByPrimaryKeySelective(OmsOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order_item
     *
     * @mbggenerated Sat Dec 19 17:57:08 CST 2020
     */
    int updateByPrimaryKey(OmsOrderItem record);
}